joque: joque::exec_coro Class Reference
joque::exec_coro Class Reference
#include <exec.hpp>
Classes
struct promise_type
Public Member Functions
exec_coro (std::coroutine_handle< promise_type > h)
exec_coro (exec_coro &&other) noexcept
exec_coro & operator= (exec_coro &&other) noexcept
bool done () const
exec_record * result ()
void tick ()
exec_record * run ()
~exec_coro ()
Constructor & Destructor Documentation
exec_coro() [1/2]
joque::exec_coro::exec_coro (std::coroutine_handle< promise_type > h) inline
exec_coro() [2/2]
joque::exec_coro::exec_coro (exec_coro && other) inline noexcept
~exec_coro()
joque::exec_coro::~exec_coro () inline
Member Function Documentation
done()
bool joque::exec_coro::done () const inline
operator=()
exec_coro& joque::exec_coro::operator= (exec_coro && other) inline noexcept
result()
exec_record* joque::exec_coro::result () inline
run()
exec_record* joque::exec_coro::run () inline
References done(), result(), and tick().
tick()
void joque::exec_coro::tick () inline
The documentation for this class was generated from the following file:
include/joque/exec.hpp