joque: joque::bits::list< ListHeader > Class Template Reference
joque::bits::list< ListHeader > Class Template Reference
#include <list.hpp>
Public Types
using header_type = ListHeader
using node_type = typename header_type::node_type
using accessor_type = typename header_type::accessor_type
using iterator = list_iterator< header_type >
using const_iterator = list_iterator< const header_type >
using ptr_type = list_ptr< node_type, header_type, accessor_type >
Public Member Functions
list ()=default
list (const list &)=delete
list (list &&)=default
list & operator= (const list &)=delete
list & operator= (list &&)=default
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
node_type & front ()
const node_type & front () const
node_type & back ()
const node_type & back () const
template<typename... Args>
node_type & emplace_front (Args &&... args)
void link_front (node_type &node)
bool empty () const
void clear_if (auto &&f)
~list ()
Member Typedef Documentation
header_type
template<typename ListHeader > using joque::bits::list< ListHeader >::header_type = ListHeader
node_type
template<typename ListHeader > using joque::bits::list< ListHeader >::node_type = typename header_type::node_type
accessor_type
template<typename ListHeader > using joque::bits::list< ListHeader >::accessor_type = typename header_type::accessor_type
iterator
template<typename ListHeader > using joque::bits::list< ListHeader >::iterator = list_iterator< header_type >
const_iterator
template<typename ListHeader > using joque::bits::list< ListHeader >::const_iterator = list_iterator< const header_type >
ptr_type
template<typename ListHeader > using joque::bits::list< ListHeader >::ptr_type = list_ptr< node_type, header_type, accessor_type >
Constructor & Destructor Documentation
list() [1/3]
template<typename ListHeader > joque::bits::list< ListHeader >::list () default
list() [2/3]
template<typename ListHeader > joque::bits::list< ListHeader >::list (const list< ListHeader > &) delete
list() [3/3]
template<typename ListHeader > joque::bits::list< ListHeader >::list (list< ListHeader > &&) default
~list()
template<typename ListHeader > joque::bits::list< ListHeader >::~list
References joque::bits::list_delete_all_next().
Member Function Documentation
operator=() [1/2]
template<typename ListHeader > list& joque::bits::list< ListHeader >::operator= (const list< ListHeader > &) delete
operator=() [2/2]
template<typename ListHeader > list& joque::bits::list< ListHeader >::operator= (list< ListHeader > &&) default
begin() [1/2]
template<typename ListHeader > list< ListHeader >::iterator joque::bits::list< ListHeader >::begin
begin() [2/2]
template<typename ListHeader > list< ListHeader >::const_iterator joque::bits::list< ListHeader >::begin
end() [1/2]
template<typename ListHeader > list< ListHeader >::iterator joque::bits::list< ListHeader >::end
end() [2/2]
template<typename ListHeader > list< ListHeader >::const_iterator joque::bits::list< ListHeader >::end
front() [1/2]
template<typename ListHeader > node_type& joque::bits::list< ListHeader >::front () inline
References joque::bits::list< ListHeader >::begin().
front() [2/2]
template<typename ListHeader > const node_type& joque::bits::list< ListHeader >::front () const inline
References joque::bits::list< ListHeader >::begin().
back() [1/2]
template<typename ListHeader > node_type& joque::bits::list< ListHeader >::back () inline
References joque::bits::list< ListHeader >::end().
back() [2/2]
template<typename ListHeader > const node_type& joque::bits::list< ListHeader >::back () const inline
References joque::bits::list< ListHeader >::end().
emplace_front()
template<typename ListHeader > template<typename... Args> list< ListHeader >::node_type & joque::bits::list< ListHeader >::emplace_front (Args &&... args)
References joque::bits::list_emplace_next().
link_front()
template<typename ListHeader > void joque::bits::list< ListHeader >::link_front (node_type & node)
References joque::bits::list_link_next().
empty()
template<typename ListHeader > bool joque::bits::list< ListHeader >::empty
clear_if()
template<typename ListHeader > void joque::bits::list< ListHeader >::clear_if (auto && f)
References joque::f.
The documentation for this class was generated from the following file:
include/joque/bits/list.hpp