name: publish

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-22.04	
        steps:
            - uses: DenverCoder1/doxygen-github-pages-action@v1
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
