name: test

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-22.04	
        steps:
          - name: configure
            run: make configure
          
          - name: build
            run: make build
          
          - name: test
            run: make test
